"""Description of changes

Revision ID: 62343b527934
Revises: 0001
Create Date: 2025-09-04 19:21:08.490016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62343b527934'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_id', table_name='tasks')
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.create_index('idx_tasks_id', 'tasks', ['id'], unique=False)
    # ### end Alembic commands ###